### ISSUE TITLE
[Matrix Vision] Either channel "PointCloud" or "PointCloudMapped" is not correctly implemented

### ISSUE THREAD

**Issue by sisiplac** [Metrilus/MetriCam2#128]
The two channels are based on the same intrinsics, so one of them is not correctly implemented.
The same holds for the channels "Distance" and "DistanceMapped", which are based on the underlying 3-D channels.
I would propose to look at a white wall and inspect which of the two 3-D channels is correct. Then either delete the channels corresponding to the defect point cloud or contact MV support team on how to extract the intrinsics correctly.

**Comment by jangernert** [comment]
Took the images of raw and mapped channel of a plain surface, converted them to a pointcloud and loaded them into a viewer application. There was no visible distortion in either of the two pointclouds.
@sisiplac should we close this?

**Comment by sisiplac** [comment]
Yes - it can be closed! I assume that the images of all three sensors of the Matrix vision are rectified, whereas the rectified images share the same intrinsics.
