### ISSUE TITLE
Consider including OpenNI2 redist with Orbbec camera

### ISSUE THREAD

**Issue by f00f** [Metrilus/MetriCam2#166]
Why are we not bundling the OpenNI2 redist files with MetriCam 2?

OpenNI2 is licensed under Apache license, so we should be fine.

**Comment by sisiplac** [comment]
I think this is a good idea!
We will also need to clarify the license of orbbec.dll, located in the subdirectory OpenNI2\Drivers. I am not sure under which license this library is released.

**Comment by f00f** [comment]
Will become obsolete once we publish nuget packages for the cameras (#210)
