### ISSUE TITLE
Avoid z-offset in Sick Visionary-T Calc3D

### ISSUE THREAD

**Issue by sisiplac** [Metrilus/MetriCam2#188]
We should skip applying an offset to the z-component of the point cloud. Since we are estimating the Brown-Conrady intrinsics based on the point cloud in other projects, this is a severe problem. I don't know exactly what `f2rc` should represent, but it could be the distance between real ToF camera origin an the front plane of the housing.
https://github.com/Metrilus/MetriCam2/blob/a640c457bbdb2b1bb83412b201c490edd2aab1d8/BetaCameras/Sick.VisionaryT/VisionaryT.cs#L463

@f00f 
@mischastik 
@jangernert 
What do you think?

**Comment by f00f** [comment]
I agree that the current practice sounds dangerous.

- What value does `f2rc` have?
- Is there maybe some hint in Sick's sample code?
- Can we simply measure if that's the offset between sensor and housing?

Other minor issues that could be changed at the same time:

- Get rid of the `* 1000` and `/= 1000`
- `depth` should be renamed to `distance`

**Comment by sisiplac** [comment]
Since I'm also interested in the value for the original z-offset, I will look it up today or tomorrow and give feedback here.

**Comment by sisiplac** [comment]
Z-offset was 15.4 mm, so it is very likely the distance between front plane of housing and focal point.
