### ISSUE TITLE
Create and publish Nuget packages

### ISSUE THREAD

**Issue by sisiplac** [Metrilus/MetriCam2#210]
As a first step, I would recommend to create and publish Nuget packages for the following projects, which are based on either no or publically available Nuget-SDKs:
* MetriCam2
* MetriCam2.Controls
* MetriCam2.Cameras.Kinect4Azure
* MetriCam2.Cameras.Kinect2  (requires switching to Nuget package)
* MetriCam2.Cameras.BaslerACE (requires switching to Nuget package)

Task #209 should be implemented before.

**Comment by f00f** [comment]
Basler Ace could also be pushed once we use the Pylon nuget package

**Comment by f00f** [comment]
Closed by #217 
Basler was not converted to nuget package as consuming their nuget package was not straight-forward.
