### ISSUE TITLE
System.Drawing.Icon in auto generated resource file

### ISSUE THREAD

**Issue by jangernert** [Metrilus/MetriCam2#76]
C# camera implementations generate a `Resources.Designer.cs` file from `Resources.resx` containing a `System.Drawing.Icon`. This obviously doesn't work for the NetStandard version of the project.
One could ifdef the declaration of the resource. But since the file is auto generated all changes would be lost upon regeneration of the file.
Any idea how to handle this properly?

```
internal static System.Drawing.Icon RealSense2Icon {
	get {
		object obj = ResourceManager.GetObject("RealSense2Icon", resourceCulture);
		return ((System.Drawing.Icon)(obj));
	}
}
```

**Comment by f00f** [comment]
For now the Resources are simply excluded from .NetStandard.
If we encounter the case where a project has Resources which we need in .NetStandard and others which we cannot use in .NetStandard, can we have a second Resources file? Should be no problem IMO.
